services:
  server:
    build:
      dockerfile: Dockerfile-server
    networks:
        - login-network
  client:
    build:
      dockerfile: Dockerfile-client
    networks:
      - login-network
    depends_on:
      - server
networks:
  login-network:
    driver: bridge