FROM eclipse-temurin

RUN mkdir /usr/src/server
RUN mkdir /usr/serverData

COPY serverData serverData

WORKDIR /usr/src/server

COPY src/TCPServer.java TCPServer.java
COPY src/Worker.java Worker.java

RUN javac *.java

CMD ["java", "TCPServer"]